config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampleapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye from Rails!!!!!!</h1>
<p>It was nice meeting you...</p>
<p>
  <%=link_to 'hello again' , say_hello_path%>
</p>

app/views/say/hello.html.erb
<h1>Hai from Rails!!!!!!</h1>
<p>rails is awesome</p>
<p>
  IT IS NOW <%= @time %>
</p>

<p>
Addition: <%= 1+2 %>
</br>
Concatenation: <%= "cow"+"goat"%>
</br>
Time in one hour :<%= 1.hour.from_now.localtime%>
</p>
<p>
  THe FILES ARE:
  <%=@files%>
</p>
<p>
  Now it's time to say
  <%=link_to 'Goodbye',say_goodbye_path%>
</p>